spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: dbmanager
  datasource:
    url: jdbc:postgresql://localhost:5432/dbmanager
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect